#line 2 "scanner.yy.c"

#line 4 "scanner.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 93
#define YY_END_OF_BUFFER 94
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[345] =
    {   0,
       87,   87,   94,   92,   90,   89,   87,   92,   69,   84,
       85,   67,   65,   81,   66,   92,   68,   63,   83,   86,
       74,   73,   75,   62,   62,   62,   62,   20,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       77,   78,   70,   91,   87,    0,   61,    0,    0,    0,
       63,   79,   88,    0,   82,   80,   71,   76,   72,   62,
       62,   62,   62,   62,   62,   62,   62,    7,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   45,   62,   62,   62,   62,
       55,   62,   62,   62,   62,   91,    0,    0,    0,    0,

       60,   64,   62,   62,   62,   12,   13,   62,   62,   62,
       62,   62,   62,   62,   21,   62,   62,   62,   62,   62,
       62,   62,   62,   36,   62,   62,   62,   62,   62,   62,
       62,   43,   62,   62,   62,   62,   62,   50,   62,   62,
       62,   62,   62,   62,    4,   62,   62,   59,    0,   62,
       62,   62,   62,   15,   62,   62,   62,   62,   62,   62,
       62,   62,   26,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   38,   62,   62,   62,   62,   62,   62,
       62,   47,   62,   62,   62,   51,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   16,   17,   62,   19,

       62,   23,   62,   62,   27,   62,   62,   62,   62,   62,
       62,   62,   34,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   48,   49,   62,   62,   62,   56,
       57,   62,    6,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   35,
        2,   62,   62,   62,    9,   40,   41,   62,   62,   62,
       62,   53,   62,   62,   62,   62,   11,   62,   62,   62,
       62,   24,   62,   62,   62,   62,   62,   31,   62,   62,
        5,   62,   62,   42,   62,   62,   62,   54,   62,   62,
       62,   62,   62,   62,   22,   25,   62,   62,   62,   62,

       62,   62,   62,   62,   62,   62,   62,   62,   10,    1,
       14,    8,   62,   62,   62,   62,   30,   62,   33,   62,
       39,   44,   46,   62,   62,   18,   62,   62,   29,   62,
       37,   62,   58,   62,   28,   62,   62,    3,   62,   52,
       62,   62,   32,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    1,    1,    6,    1,    1,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   16,   17,   18,
       19,   20,    1,    1,   21,   22,   23,   24,   25,   26,
       27,   28,   29,   30,   30,   31,   32,   33,   34,   35,
       36,   37,   38,   39,   40,   41,   30,   42,   30,   30,
       43,    1,   44,   45,    1,    1,   46,   47,   48,   49,

       50,   51,   52,   53,   54,   30,   30,   55,   56,   57,
       58,   59,   60,   61,   62,   63,   64,   65,   30,   66,
       30,   30,   67,   68,    1,    1,    1,   69,   69,   69,
       69,    1,    1,    1,   69,   69,   69,    1,    1,    1,
       69,    1,   69,    1,   69,    1,   69,   69,   69,   69,
        1,    1,    1,   69,    1,    1,    1,    1,    1,   69,
       69,   69,   69,    1,    1,    1,   69,   69,   69,   69,
        1,    1,   69,    1,   69,    1,   69,    1,   69,   69,
       69,   69,    1,    1,    1,   69,    1,    1,    1,    1,
        1,    1,    1,    1,   69,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[70] =
    {   0,
        1,    1,    2,    3,    3,    1,    1,    1,    3,    3,
        1,    3,    3,    3,    1,    1,    1,    1,    1,    1,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    1,    1,    1,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    1,    3,    3
    } ;

static yyconst flex_int16_t yy_base[352] =
    {   0,
        0,    0,  158,  781,  781,  781,  153,   66,  781,  781,
      781,  781,  781,  781,  139,  140,    0,   59,  127,  781,
       65,  781,  122,   50,    0,   61,   67,   68,   97,   40,
       74,  102,   69,   46,  118,   77,   79,   91,  119,   80,
      781,  781,  781,    0,   96,  158,  781,  173,  184,  195,
      134,  781,    0,   79,  781,  781,  781,  781,  781,    0,
      165,  114,  136,  156,  173,  181,  161,  180,  160,  178,
      182,  180,  191,  188,  190,  204,  195,  198,  204,  203,
      205,  224,  226,  221,  227,  221,  228,  223,  230,  256,
      236,  238,  235,  237,  240,    0,  304,  316,  327,  338,

      781,   78,  257,  247,  242,    0,    0,  265,  265,  275,
      258,  289,  293,    0,    0,  295,  303,  319,  317,  306,
      387,  322,  331,  333,  339,  327,  335,  326,  327,    0,
      348,    0,  338,  337,  350,  337,  338,    0,  355,  350,
      363,  353,  372,  376,    0,  378,  370,    0,  430,  382,
      386,  387,  406,    0,  394,  411,  402,  423,  430,  419,
      425,  433,    0,  427,  431,  430,  424,  444,  434,  441,
      448,  441,  442,    0,  451,  459,  440,  451,  470,  477,
      470,    0,  472,  480,  483,    0,  471,  474,  478,  477,
      494,  480,  485,  491,  481,  488,    0,    0,  492,    0,

      496,    0,  503,  496,    0,  505,  503,  519,  511,  512,
      516,  517,    0,  520,  521,  521,  522,  521,  528,  541,
      542,  535,  545,  547,    0,    0,  547,  551,  542,    0,
        0,  553,    0,  543,  542,  551,  554,  563,  567,  555,
      577,  579,  569,  566,  573,  578,  587,  587,  583,    0,
        0,  580,  581,  591,    0,    0,    0,  582,  583,  600,
      593,    0,  599,  603,  600,  600,    0,  594,  599,  601,
      608,    0,  614,  611,  629,  621,  634,    0,  632,  620,
        0,  629,  631,    0,  642,  627,  635,    0,  639,  636,
      637,  641,  649,  640,    0,    0,  649,  648,  651,  650,

      663,  669,  657,  675,  675,  666,  677,  669,    0,    0,
        0,    0,  673,  670,  671,  690,    0,  684,    0,  693,
        0,    0,    0,  684,  684,    0,  687,  686,    0,  690,
        0,  686,    0,  692,    0,  703,  698,    0,  702,    0,
      698,  706,    0,  781,  762,  766,   79,  770,  772,  774,
      776
    } ;

static yyconst flex_int16_t yy_def[352] =
    {   0,
      344,    1,  344,  344,  344,  344,  344,  345,  344,  344,
      344,  344,  344,  344,  344,  344,  346,  344,  344,  344,
      344,  344,  344,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      344,  344,  344,  348,  344,  349,  344,  350,  345,  350,
      344,  344,  346,  344,  344,  344,  344,  344,  344,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  348,  349,  349,  349,  351,

      344,  344,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  351,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,

      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,

      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,    0,  344,  344,  344,  344,  344,  344,
      344
    } ;

static yyconst flex_int16_t yy_nxt[851] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   25,   25,   30,   25,
       31,   32,   33,   34,   35,   25,   36,   37,   38,   25,
       39,   40,   41,   42,   43,   24,   25,   26,   27,   28,
       29,   25,   25,   30,   31,   32,   33,   34,   35,   25,
       36,   37,   38,   25,   39,   40,   44,    4,    4,   46,
       47,   54,   76,   51,   48,   48,   56,   48,   48,   48,
       61,   65,   60,   57,   58,   86,   62,   63,   64,   84,
       70,   68,  102,  102,   66,   69,   76,   67,   77,   45,

       71,   90,   78,   91,   61,   72,   65,   79,   85,   86,
       62,   63,   64,   95,   84,   70,   68,   73,   66,   92,
       69,   67,   80,   77,   71,   74,   90,   78,   91,   72,
       81,   79,   85,   48,   50,   82,   75,   95,   87,   93,
       59,   83,   73,   94,   92,   55,   54,   80,   51,  105,
       74,   88,   52,   51,   89,   81,   45,  344,  106,   82,
       75,   46,   47,   87,   93,   83,   97,   97,   94,   97,
       97,   97,  344,  105,  344,   88,   99,   47,   89,  344,
      107,   48,   48,  106,   48,   48,   48,  100,  101,  103,
      344,  104,   48,   48,  112,   48,   48,   48,   99,   47,

      114,  113,  118,   48,   48,  107,   48,   48,   48,  108,
      109,  115,  110,  119,  103,  111,  104,  116,  112,  121,
      117,  120,  122,  125,  114,   97,  113,  118,  344,  126,
      127,  128,  123,  108,  109,  115,  110,  129,  119,  111,
       48,  116,  124,  121,  117,  120,  122,  130,  125,  131,
      344,   48,   50,  126,  132,  127,  128,  123,  133,  134,
      138,  129,   48,  139,  135,  136,  124,  137,  143,  144,
      344,  145,  130,  146,  131,  147,  140,  150,  132,  148,
      151,  152,  133,  134,  138,  153,  156,  139,  135,  136,
      141,  137,  143,  144,  142,  145,  344,  146,  154,  147,

      344,  140,  150,  148,  151,  152,  344,   99,   47,  155,
      153,  156,   97,   97,  141,   97,   97,   97,  142,   99,
       47,  157,  154,  160,   97,   97,  344,   97,   97,   97,
       99,   47,  158,  155,  159,   97,   97,  163,   97,   97,
       97,   99,   47,  164,  171,  157,   97,   97,  160,   97,
       97,   97,  161,  172,  344,  162,  158,  173,  159,  174,
      344,  175,  163,  176,  344,  177,  178,  164,  179,  171,
      182,   97,  180,  181,  183,  184,  161,  185,  172,  162,
      186,  344,  173,   97,  174,  175,  188,  344,  176,  177,
      178,  187,  189,  179,   97,  182,  180,  181,  183,  184,

      190,  191,  185,  192,  186,   97,   98,  165,  344,  344,
      188,  166,  167,  344,  344,  195,  187,  189,  344,  344,
      193,  168,  194,  169,  170,  190,  191,  192,  196,  344,
      197,  198,  165,  100,  101,  199,  166,  167,   97,   97,
      195,   97,   97,   97,  193,  168,  194,  169,  170,  200,
      201,  344,  202,  196,  197,  203,  198,  204,  212,  199,
      205,  206,  207,  209,  210,  213,  344,  208,  214,  215,
      216,  218,  344,  344,  200,  201,  202,  220,  217,  203,
      211,  219,  204,  212,  205,  206,  207,  209,  221,  210,
      213,  208,  222,  214,  215,  216,  218,   97,   98,  223,

      226,  220,  217,  224,  211,  225,  219,  227,  344,  228,
      229,  230,  221,  231,  232,  344,  233,  222,  234,  235,
      344,  236,  237,  239,  223,  226,  238,  224,  240,  225,
      241,  243,  227,  228,  229,  230,  242,  231,  244,  232,
      233,  245,  234,  246,  235,  236,  237,  239,  247,  248,
      238,  249,  240,  250,  251,  241,  243,  252,  253,  254,
      242,  255,  244,  256,  257,  259,  245,  246,  258,  260,
      261,  262,  247,  248,  263,  249,  264,  250,  251,  265,
      266,  252,  253,  254,  267,  255,  268,  269,  256,  257,
      259,  270,  258,  271,  260,  261,  262,  272,  263,  273,

      277,  264,  274,  265,  266,  275,  276,  278,  267,  279,
      268,  280,  269,  281,  282,  283,  270,  271,  284,  285,
      286,  287,  272,  288,  273,  277,  274,  289,  290,  275,
      276,  291,  278,  292,  279,  293,  280,  281,  282,  294,
      283,  295,  284,  285,  296,  286,  287,  297,  288,  298,
      344,  299,  289,  290,  300,  291,  301,  292,  302,  293,
      303,  304,  305,  294,  306,  295,  307,  308,  296,  309,
      310,  297,  311,  312,  298,  299,  313,  314,  316,  300,
      315,  301,  302,  317,  303,  304,  318,  305,  306,  319,
      307,  320,  308,  309,  310,  321,  311,  322,  312,  323,

      313,  324,  314,  316,  315,  325,  326,  317,  327,  328,
      329,  318,  330,  331,  319,  320,  332,  333,  334,  335,
      321,  336,  322,  323,  337,  338,  324,  339,  344,  325,
      326,  340,  327,  328,  341,  329,  342,  330,  331,  343,
      332,  333,  334,  335,  344,  336,  344,  344,  337,  338,
      344,  344,  339,  344,  344,  340,  344,  344,  341,  344,
      342,  344,  344,  343,   49,   49,   53,  344,   53,   53,
       96,  344,   96,   96,   98,   98,   50,   50,  149,  149,
        3,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,

      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344
    } ;

static yyconst flex_int16_t yy_chk[851] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    8,
        8,   18,   30,   18,    8,    8,   21,    8,    8,    8,
       24,   26,  347,   21,   21,   34,   24,   24,   24,   33,
       28,   27,  102,   54,   26,   27,   30,   26,   31,   45,

       28,   36,   31,   37,   24,   28,   26,   31,   33,   34,
       24,   24,   24,   40,   33,   28,   27,   29,   26,   38,
       27,   26,   32,   31,   28,   29,   36,   31,   37,   28,
       32,   31,   33,    8,    8,   32,   29,   40,   35,   39,
       23,   32,   29,   39,   38,   19,   51,   32,   51,   62,
       29,   35,   16,   15,   35,   32,    7,    3,   63,   32,
       29,   46,   46,   35,   39,   32,   46,   46,   39,   46,
       46,   46,    0,   62,    0,   35,   48,   48,   35,    0,
       64,   48,   48,   63,   48,   48,   48,   49,   49,   61,
        0,   61,   49,   49,   67,   49,   49,   49,   50,   50,

       69,   68,   72,   50,   50,   64,   50,   50,   50,   65,
       65,   70,   66,   73,   61,   66,   61,   71,   67,   74,
       71,   73,   75,   77,   69,   46,   68,   72,    0,   78,
       79,   80,   76,   65,   65,   70,   66,   81,   73,   66,
       48,   71,   76,   74,   71,   73,   75,   82,   77,   83,
        0,   49,   49,   78,   84,   79,   80,   76,   85,   86,
       88,   81,   50,   89,   87,   87,   76,   87,   91,   92,
        0,   93,   82,   94,   83,   94,   90,  103,   84,   95,
      104,  105,   85,   86,   88,  108,  111,   89,   87,   87,
       90,   87,   91,   92,   90,   93,    0,   94,  109,   94,

        0,   90,  103,   95,  104,  105,    0,   97,   97,  110,
      108,  111,   97,   97,   90,   97,   97,   97,   90,   98,
       98,  112,  109,  117,   98,   98,    0,   98,   98,   98,
       99,   99,  113,  110,  116,   99,   99,  119,   99,   99,
       99,  100,  100,  120,  122,  112,  100,  100,  117,  100,
      100,  100,  118,  123,    0,  118,  113,  124,  116,  125,
        0,  126,  119,  127,    0,  128,  129,  120,  131,  122,
      135,   97,  133,  134,  136,  137,  118,  139,  123,  118,
      140,    0,  124,   98,  125,  126,  142,    0,  127,  128,
      129,  141,  143,  131,   99,  135,  133,  134,  136,  137,

      144,  146,  139,  147,  140,  100,  100,  121,    0,    0,
      142,  121,  121,    0,    0,  152,  141,  143,    0,    0,
      150,  121,  151,  121,  121,  144,  146,  147,  153,    0,
      155,  156,  121,  149,  149,  157,  121,  121,  149,  149,
      152,  149,  149,  149,  150,  121,  151,  121,  121,  158,
      159,    0,  160,  153,  155,  161,  156,  162,  169,  157,
      164,  165,  166,  167,  168,  170,    0,  166,  171,  172,
      173,  175,    0,    0,  158,  159,  160,  177,  173,  161,
      168,  176,  162,  169,  164,  165,  166,  167,  178,  168,
      170,  166,  179,  171,  172,  173,  175,  149,  149,  180,

      184,  177,  173,  181,  168,  183,  176,  185,    0,  187,
      188,  189,  178,  190,  191,    0,  192,  179,  193,  194,
        0,  195,  196,  199,  180,  184,  196,  181,  201,  183,
      203,  206,  185,  187,  188,  189,  204,  190,  207,  191,
      192,  208,  193,  209,  194,  195,  196,  199,  210,  211,
      196,  212,  201,  214,  215,  203,  206,  216,  217,  218,
      204,  219,  207,  220,  221,  223,  208,  209,  222,  224,
      227,  228,  210,  211,  229,  212,  232,  214,  215,  234,
      235,  216,  217,  218,  236,  219,  237,  238,  220,  221,
      223,  239,  222,  240,  224,  227,  228,  241,  229,  242,

      246,  232,  243,  234,  235,  244,  245,  247,  236,  248,
      237,  249,  238,  252,  253,  254,  239,  240,  258,  259,
      260,  261,  241,  263,  242,  246,  243,  264,  265,  244,
      245,  266,  247,  268,  248,  269,  249,  252,  253,  270,
      254,  271,  258,  259,  273,  260,  261,  274,  263,  275,
        0,  276,  264,  265,  277,  266,  279,  268,  280,  269,
      282,  283,  285,  270,  286,  271,  287,  289,  273,  290,
      291,  274,  292,  293,  275,  276,  294,  297,  299,  277,
      298,  279,  280,  300,  282,  283,  301,  285,  286,  302,
      287,  303,  289,  290,  291,  304,  292,  305,  293,  306,

      294,  307,  297,  299,  298,  308,  313,  300,  314,  315,
      316,  301,  318,  320,  302,  303,  324,  325,  327,  328,
      304,  330,  305,  306,  332,  334,  307,  336,    0,  308,
      313,  337,  314,  315,  339,  316,  341,  318,  320,  342,
      324,  325,  327,  328,    0,  330,    0,    0,  332,  334,
        0,    0,  336,    0,    0,  337,    0,    0,  339,    0,
      341,    0,    0,  342,  345,  345,  346,    0,  346,  346,
      348,    0,  348,  348,  349,  349,  350,  350,  351,  351,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,

      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[94] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
#line 5 "scanner.l"
#include <stdio.h>
#include <stdlib.h>
#line 781 "scanner.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 10 "scanner.l"

#line 965 "scanner.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 345 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 781 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 11 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 12 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 13 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 14 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 15 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 16 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 17 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 18 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 19 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 20 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 21 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 22 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 23 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 24 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 25 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 26 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 27 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 28 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 29 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 30 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 31 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 32 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 33 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 34 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 35 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 36 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 37 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 38 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 39 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 40 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 41 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 42 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 43 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 44 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 45 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 46 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 47 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 48 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 49 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 50 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 51 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 52 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 53 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 54 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 55 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 56 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 57 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 58 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 59 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 60 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 61 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 62 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 63 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 64 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 65 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 66 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 67 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 68 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 69 "scanner.l"
{printf("PALAVRA RESERVADA: %s\n", yytext);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 71 "scanner.l"
{printf("IDENTIFICADOR: %s\n", yytext);}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 73 "scanner.l"
{printf("LITERAL: %s\n", yytext);}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 75 "scanner.l"
{printf("VARIÁVEL: %s\n", yytext);}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 77 "scanner.l"
{printf("INTEIRO: %s\n", yytext);}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 78 "scanner.l"
{printf("REAL: %s\n", yytext);}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 80 "scanner.l"
{printf("OPERADOR ARITMETICO: %s\n", yytext);}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 81 "scanner.l"
{printf("OPERADOR ARITMETICO: %s\n", yytext);}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 82 "scanner.l"
{printf("OPERADOR ARITMETICO: %s\n", yytext);}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 83 "scanner.l"
{printf("OPERADOR ARITMETICO: %s\n", yytext);}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 84 "scanner.l"
{printf("OPERADOR ARITMETICO: %s\n", yytext);}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 85 "scanner.l"
{printf("OPERADOR ARITMETICO: %s\n", yytext);}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 87 "scanner.l"
{printf("OPERADOR RELACIONAL: %s\n", yytext);}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 88 "scanner.l"
{printf("OPERADOR RELACIONAL: %s\n", yytext);}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 89 "scanner.l"
{printf("OPERADOR RELACIONAL: %s\n", yytext);}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 90 "scanner.l"
{printf("OPERADOR RELACIONAL: %s\n", yytext);}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 91 "scanner.l"
{printf("OPERADOR RELACIONAL: %s\n", yytext);}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 92 "scanner.l"
{printf("OPERADOR RELACIONAL: %s\n", yytext);}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 94 "scanner.l"
{printf("SIMBOLO ESPECIAL: %s\n", yytext);}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 95 "scanner.l"
{printf("SIMBOLO ESPECIAL: %s\n", yytext);}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 96 "scanner.l"
{printf("SIMBOLO ESPECIAL: %s\n", yytext);}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 97 "scanner.l"
{printf("SIMBOLO ESPECIAL: %s\n", yytext);}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 98 "scanner.l"
{printf("SIMBOLO ESPECIAL: %s\n", yytext);}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 99 "scanner.l"
{printf("SIMBOLO ESPECIAL: %s\n", yytext);}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 100 "scanner.l"
{printf("SIMBOLO ESPECIAL: %s\n", yytext);}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 101 "scanner.l"
{printf("SIMBOLO ESPECIAL: %s\n", yytext);}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 102 "scanner.l"
{printf("SIMBOLO ESPECIAL: %s\n", yytext);}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 103 "scanner.l"
{printf("SIMBOLO ESPECIAL: %s\n", yytext);}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 105 "scanner.l"
{ /* ignore white space */ }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 107 "scanner.l"
{ /* ignore white space */ }
	YY_BREAK
case 89:
/* rule 89 can match eol */
YY_RULE_SETUP
#line 109 "scanner.l"
{ /* ignore white space */ }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 111 "scanner.l"
{ /* ignore white space */ }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 113 "scanner.l"
{ /* ignore white space */ }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 115 "scanner.l"
{ printf("Mystery character: %s\n", yytext); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 117 "scanner.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1524 "scanner.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 345 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 345 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 344);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 117 "scanner.l"



int main(int argc, char **argv) {

  if(argc < 2) { /* just read stdin */
    yylex();
  } else {

    int i = 0;

    for(i = 1; i < argc; i++) {

      FILE *f = fopen(argv[i], "r");
    
      if(!f) {
        perror(argv[1]);
        return (1);
      }

      yyrestart(f);
      yylex();
      fclose(f);
    }
  }

  return 0;
}
